"""
Credit/Ledger Models

Pydantic models for tracking organization credit usage in the credit_usage table.
"""
from typing import Optional, Any, Dict
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum

# 1. Static Enum for the 'query_type' column
class QueryType(str, Enum):
    """Defines the billable actions in the system."""
    TEXT_QUERY = "text_query"    # For any chatting/LLM inference
    UPLOAD_FILE = "upload_file"  # For any file chunking/embedding

# 2. Static Enum for the 'status' column
class QueryStatus(str, Enum):
    COMPLETED = "completed"
    FAILED = "failed"
    PENDING = "pending"

# 3. Base Schema perfectly mapped to the credit_usage columns
class CreditUsageBase(BaseModel):
    """Base schema mirroring the credit_usage table columns."""
    query_type: QueryType = Field(..., description="The category of the billable action")
    query_text: str = Field(..., description="Description or snippet of the query")
    credits_used: int = Field(..., description="Integer credits deducted from subscription")
    status: QueryStatus = Field(default=QueryStatus.COMPLETED, description="Status of the transaction")
    input_tokens: int = Field(default=0, description="Tokens sent to AI")
    output_tokens: int = Field(default=0, description="Tokens generated by AI")
    cost: float = Field(default=0.0, description="Actual monetary cost of the API call (numeric)")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Extra details (e.g., chat_id, message_id)")

# 4. Create Schema (Input)
class CreditUsageCreate(CreditUsageBase):
    """Schema for creating a new usage log (includes the organization_id)"""
    organization_id: str = Field(..., description="Organization UUID")

# 5. Response Schema (Output from DB)
class CreditUsage(CreditUsageBase):
    """Schema for returning a usage log to the frontend"""
    id: str = Field(..., description="Transaction UUID")
    organization_id: str = Field(..., description="Organization UUID")
    created_at: datetime = Field(..., description="Transaction timestamp")

    class Config:
        from_attributes = True